dist: trusty

notifications:
  email:
    recipients:
      - openmessaging@googlegroups.com
  on_success: change
  on_failure: always

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

script:
  - mvn clean install
